nome = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome...\n')
m = nome.upper()
n = nome.lower()
o = len(nome)-nome.count(' ')
p = nome.split()
print('Seu nome em maiúsculas é {}'.format(m))
print('Seu nome em minúsculas é {}'.format(n))
print('Seu nome ao todo tem {} letras'.format(o))
print('Seu primeiro nome é {}'.format(p[0]))
print('E seu primeiro nome possuí {} letras'.format(len(p[0])))
